description = """
## Documentation

The API is a RESTful web service that provides access to the data stored in the database and integrates KPI Engine, Anomaly Detection and RAG features. The API is built using FastAPI, a modern Python web framework that provides automatic generation of OpenAPI documentation. The API is hosted on Google Cloud Run and is available at `https://<base_url>/api/<api-version>`. The API version is specified in the URL and should be one of the following values: `v1.0`. The latest version of the API is `v1.0`. The API is secured using firebase authentication and authorization, and the user must provide a valid JWT token in the `Authorization` header to access the endpoints. Https is enforced for all requests to the API from Cloud Run.

The <base_url> will be provided by the project maintainers to who is interested in using the API.

The API documentation is available at `https://<base_url>/api/<api-version>/docs` as a Swagger UI interface. The documentation provides information about the available endpoints, request and response formats, and examples. For an alternative view, the API documentation is also available at `https://<base_url>/api/<api-version>/redoc`. The documentation is automatically generated by FastAPI based on the code and docstrings.

### Usage
To use the API, the user must provide a valid JWT token in the `Authorization` header. The token can be obtained by calling the test `user/login` endpoint with the user's email and password. The token is valid for 1 hour for security reasons. If the token expires, the user must obtain a new token by calling the `user/login` endpoint again.

In order to test the API using the Swagger UI interface, the user must first authorize the requests by providing the JWT token in the `Authorize` button:
1. Run the test `user/login` api call to simulate a login from the frontend.
    - user: ffm@example.com
	- password: passwordffm
2. Copy the returned token, click on the green button 'Authorize' and paste the token to unblock the api calls.

## Plugins
The API is organized in plugins, each containing a set of endpoints related to a specific functionality. The available plugins are:
- `kpi`: Key Performance Indicators
- `machine`: Machines query
- `user`: Users interaction
- `chat`: Chat interaction
- `site`: Sites query
- `report`: Reports query
- `auth`: Authentication and Authorization

## Local Development
One can always run the API locally for development purposes.
### Installation
To install locally the API, clone the repository and install the dependencies using pip:
```bash
git clone https://github.com/sa-team-d/api.git
cd api
pip install -r requirements.txt
```
### Usage
To start the API locally, run the following command:
```bash
uvicorn main:app --reload
```
or use the FastAPI command for development:
```bash
fastapi dev main.py
```
The API will be available at `http://localhost:8000/api/<api-version>`.

## Contact
For any questions or issues, please contact the project maintainers:
- [Leonardo Stoppani](https://github.com/lilf4p)
- [Oleksiy Nedobiychuk](https://github.com/lesi-nedo)
"""